изменение даты рождения и главная страничка(только по одной задаче)
devind-team/eleden pull request #105
Opened 2022-04-28 13:11 UTC by IgneusCougar

2022-04-28 13:20 UTC, Luferov requested changes
Нужно поправить код

2022-04-28 13:20 UTC, Luferov commented on client/components/raai/RaaiGoals.vue
> +  data () {
Тут должно быть composition api и функция setup

2022-04-28 13:20 UTC, Luferov commented on client/components/raai/RaaiGoals.vue
> +          icon: 'mdi-chat-question',
Везде повторяется mdi

2022-04-28 13:20 UTC, Luferov commented on client/components/raai/RaaiIndex.vue
> +    v-carousel(height="700")
Почему именно 700px?

2022-04-28 13:20 UTC, Luferov commented on client/components/raai/RaaiIndex.vue
> +      v-col(cols="12" sm="4")
Если сложить am будет 8

2022-04-28 13:20 UTC, Luferov commented on client/components/raai/RaaiNews.vue
> +  data () {
Тут должна быть функция setup

2022-04-28 13:20 UTC, Luferov commented on client/package.json
> +    "@babel/preset-env": "^7.16.11",
Откуда это?)

2022-04-28 13:22 UTC, IgneusCougar commented on client/package.json
> +    "@babel/preset-env": "^7.16.11",
Не знаю, я вроде ничего не устанавливала

2022-05-04 08:15 UTC, Luferov commented
Исправления будут?

2022-05-05 17:30 UTC, Luferov requested changes
Нужно поправить, по крайней мере оформление

2022-05-05 17:30 UTC, Luferov commented on client/components/raai/RaaiCarousel.vue
> +      ]
что-то не ровно скобка как-то...

2022-05-05 17:30 UTC, Luferov commented on client/components/raai/RaaiNews.vue
> +
тебе нужна пустая строка?

2022-05-05 17:30 UTC, Luferov commented on client/components/raai/RaaiIndex.vue
> +  components: {RaaiCarousel, RaaiGoals, PageNews},
components: { RaaiCarousel, RaaiGoals, PageNews }, <- ты жадная на пробелы?

2022-05-05 17:30 UTC, Luferov commented on client/components/raai/RaaiIndex.vue
> +import RaaiGoals from "~/components/raai/RaaiGoals.vue";
в одиночный кавычках без `;` в конце

2022-05-05 17:30 UTC, Luferov commented on client/components/raai/RaaiGoals.vue
> +    return {
может в одну строчку return { goals }

2022-05-05 17:30 UTC, Luferov commented on client/components/raai/RaaiNews.vue
> +    slot(name="card")
не понятно вообще зачем тебе этот компонент и зачем тебе слот с именем card?

2022-05-08 09:49 UTC, Luferov approved these changes

2022-05-08 10:19 UTC, merged